defaults: &defaults
  status: 0
  users:
    role_none: 0
    role_admin: 1
  home:
    site_title: "八方街"
    site_theme: "主题街"
    develop_tool: "软件街"
    study: "问答街"
    outsource: "外包街" 
    tutorial: "教程街"
  site_themes:
    max_page: 15

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
