defaults: &defaults
  status: 0
  users:
    role_none: 0
    role_admin: 1
  home:
    site_title: "森罗万象"
    site_theme: "网站主题"
    develop_tool: "开发工具"
  site_themes:
    max_page: 15

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
